import { IconInfo } from '../../components/Icons/IconInfo';

export function ManageData() {
  return (
    <>
      <div className="subtitle1 mb-8">Download your data</div>
      <div className="caption mb-8">
        You own your data. Tap the button below to download a copy of your data
      </div>
      <div className="manage-btn mb-8">
        <button className="gen-secondary-btn">Download My Data</button>
      </div>
      <div className="subtitle1 mb-8">Delete your data</div>
      <div className="caption mb-8">
        Use this only if you want to permanently delete your account & data from
        our system.
      </div>
      <div className="plate mb-8">
        <IconInfo />
        <p>
          Due to the immutable nature of distributed ledger technology, network
          nodes operated by the community may still retain historical
          transactions generated by your account, however your personally
          identifiable information such as your name, e-mail, your key-value
          storage etc will be removed. Any of your digital assets will be lost.
        </p>
      </div>
      <div className="manage-btn">
        <button className="gen-secondary-btn danger">Delete My Data</button>
      </div>
    </>
  );
}
