#!/bin/sh
# Ethora frontend image entrypoint.
#
#   ethora-frontend serve            render config from env, then run nginx
#   ethora-frontend export [/out]    render config from env into /out and exit
#                                    (for hosts whose own nginx serves the
#                                    bundle from a directory)
#   ethora-frontend render [dir]     render in place and exit
#
# Rendering does two things with the VITE_* variables in the environment:
#   1. writes config.js  -> window.__ETHORA_CONFIG__ = { VITE_...: "..." }
#      (read by src/config/env.ts before the app starts)
#   2. fills the Content-Security-Policy connect-src placeholder in
#      index.html with the origins derived from the URL-valued variables,
#      mirroring originsFrom() in vite-plugin-csp.ts
# Everything else in the bundle is identical for every install.
set -eu

HTML_DIR="${HTML_DIR:-/usr/share/nginx/html}"
PLACEHOLDER="__ETHORA_CSP_ENV_ORIGINS__"
# Keep in sync with ENV_ORIGIN_KEYS in vite-plugin-csp.ts.
ORIGIN_KEYS="VITE_API VITE_API_V2 VITE_APP_XMPP_SERVICE VITE_XMPP_HOST VITE_APP_CENTRIFUGE_SERVICE VITE_LIVEKIT_URL VITE_TRANSLATE_ENDPOINT VITE_QR_URL VITE_FIREBASE_AUTH_DOMAIN VITE_FIREBASE_STORAGE_BUCKET"

json_escape() {
  # backslash, double quote, and control characters that can appear in env
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/\t/\\t/g' | tr -d '\r\n'
}

write_config_js() {
  dir="$1"
  {
    echo "// Generated by the container entrypoint from its environment. Do not edit."
    echo "window.__ETHORA_CONFIG__ = {"
    env | grep '^VITE_' | sort | while IFS='=' read -r key value; do
      [ -z "$value" ] && continue
      printf '  "%s": "%s",\n' "$key" "$(json_escape "$value")"
    done
    echo "};"
  } > "$dir/config.js"
}

origins_from() {
  # Mirrors originsFrom() in vite-plugin-csp.ts for one value.
  v="$1"
  [ -z "$v" ] && return 0
  case "$v" in
    *://*) ;;
    *) v="https://$v" ;;
  esac
  scheme="${v%%://*}"
  rest="${v#*://}"
  hostport="${rest%%/*}"
  hostport="$(printf '%s' "$hostport" | tr 'A-Z' 'a-z')"
  host="${hostport%%:*}"
  [ -z "$host" ] && return 0
  case "$scheme" in
    https) ws="wss" ;;
    http) ws="ws" ;;
    *) ws="$scheme" ;;
  esac
  echo "$scheme://$hostport"
  echo "$ws://$hostport"
  # Three or more labels: also allow every sibling under the parent domain.
  labels="$(printf '%s' "$host" | tr '.' '\n' | wc -l | tr -d ' ')"
  if [ "$labels" -ge 3 ]; then
    parent="${host#*.}"
    echo "https://*.$parent:*"
    echo "wss://*.$parent:*"
  fi
}

csp_origins() {
  for key in $ORIGIN_KEYS; do
    eval "val=\${$key:-}"
    origins_from "$val"
  done | awk '!seen[$0]++' | tr '\n' ' ' | sed 's/ $//'
}

fill_csp() {
  dir="$1"
  origins="$(csp_origins)"
  if grep -q "$PLACEHOLDER" "$dir/index.html"; then
    # '|' is safe as a delimiter: origins contain only [A-Za-z0-9.:/*-].
    sed -i "s|$PLACEHOLDER|$origins|" "$dir/index.html"
  fi
}

render() {
  dir="$1"
  write_config_js "$dir"
  fill_csp "$dir"
  echo "[ethora-frontend] rendered config.js ($(grep -c '^  "VITE_' "$dir/config.js") keys) and CSP origins into $dir"
}

cmd="${1:-serve}"
case "$cmd" in
  serve)
    render "$HTML_DIR"
    exec nginx -g 'daemon off;'
    ;;
  export)
    out="${2:-/out}"
    mkdir -p "$out"
    # Copy first, then render in the copy so the image content stays pristine.
    cp -R "$HTML_DIR"/. "$out"/
    render "$out"
    ;;
  render)
    render "${2:-$HTML_DIR}"
    ;;
  *)
    exec "$@"
    ;;
esac
