#!/usr/bin/env node
// Copies the AI widget bundle out of node_modules into public/, and records
// where it landed in src/generated/bundledWidget.ts.
//
// Runs from the `prebuild` npm hook, i.e. before `tsc -b && vite build`, so a
// plain `npm ci && npm run build` on the server is all the deploy needs.
//
// Why the widget is a dependency at all.
//
// The embed URL used to come only from VITE_WIDGET_URL, a build-time string
// Vite inlines into this bundle. On QA it read
// https://widget.chat-qa.ethora.com/assistant2604.js: an April build sitting
// on a static host with a separate deploy nobody re-ran. Nothing tied that
// string to a version of the widget, so it rotted quietly while the admin kept
// handing operators an embed snippet for a bundle older than the
// /v2/widget/sessions flow that snippet depends on.
//
// Pinning @ethora/ai-chat-widget in package.json puts the widget under the
// lockfile: `npm ci` fetches the exact commit, this script copies it next to
// the admin's own assets, and the app serves it from its own origin. Updating
// the widget becomes a reviewable diff instead of an ssh session.

import { createHash } from 'node:crypto';
import { copyFileSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const PKG = '@ethora/ai-chat-widget';

const require = createRequire(import.meta.url);
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const die = (msg) => {
  console.error(`\n[copy-widget] ${msg}\n`);
  process.exit(1);
};

// Resolve via package.json, not the package root: "main" is an IIFE bundle,
// not something Node can import. We only need its path and its version.
let pkgJsonPath;
try {
  pkgJsonPath = require.resolve(`${PKG}/package.json`);
} catch {
  die(`${PKG} is not installed. Run npm ci (or npm i) first.`);
}

const pkg = JSON.parse(readFileSync(pkgJsonPath, 'utf8'));

// AI features disabled: with `ai_service: false` in deploy.yml the installer
// swaps in a no-op stub (version '0.0.0-deploy-stub', see
// deploy/scripts/setup-node-services.sh) instead of the real widget. That stub
// has no embed bundle, so skip the copy entirely and emit an empty path -
// widgetUrl.ts guards on BUNDLED_WIDGET_PATH being set, so the admin UI just
// doesn't offer the widget. Failing the build here would block every
// AI-disabled deploy.
if (pkg.version === '0.0.0-deploy-stub') {
  writeFileSync(
    resolve(root, 'src/generated/bundledWidget.ts'),
    `// GENERATED by scripts/copy-widget.mjs (npm prebuild). Do not edit by hand.
//
// AI features are disabled in this deploy (no-op @ethora/ai-chat-widget stub),
// so no widget bundle is shipped and the admin embed is not offered.
export const BUNDLED_WIDGET_VERSION = '';
export const BUNDLED_WIDGET_PATH = '';
`
  );
  console.log(`[copy-widget] ${PKG}@${pkg.version}: AI features disabled, skipping widget embed`);
  process.exit(0);
}

const src = resolve(dirname(pkgJsonPath), pkg.main || 'dist/ethora_assistant.js');

let bytes;
try {
  bytes = readFileSync(src);
} catch {
  die(
    `${PKG}@${pkg.version} has no bundle at ${src}.\n` +
      `  The widget repo commits dist/ethora_assistant.js precisely so a git\n` +
      `  install has one. A missing file means the pinned commit predates that.`
  );
}

// Guard against a stale or wrong install. An older revision of this package
// shipped a LIBRARY build (dist/main.js) rather than the embed bundle: a large,
// plausible-looking JS file that would copy fine and then do nothing on the
// page. Cheaper to fail the build than to debug that on QA.
const text = bytes.toString('utf8');
for (const marker of ['chat-content-assistant', 'data-app-id', 'widget/sessions']) {
  if (!text.includes(marker)) {
    die(
      `${src} is not the embed bundle: "${marker}" not found in it.\n` +
        `  Installed ${PKG}@${pkg.version}. Bump the pinned commit and reinstall.`
    );
  }
}

// Content hash, so a changed bundle is always a new URL (no stale copy served
// out of a visitor's cache) and an unchanged one is always the same URL.
const hash = createHash('sha256').update(bytes).digest('hex').slice(0, 8);
const fileName = `assistant-${hash}.js`;
const outDir = resolve(root, 'public/widget');

// Wiped first: leftovers would ship as dead multi-megabyte files still
// answering requests from embeds we would rather see fail loudly.
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });
copyFileSync(src, resolve(outDir, fileName));

// The version the bundle REPORTS on window.EthoraAssistant.version, which is
// not always the version in its package.json - a bundle built one commit
// before a version bump says the old number. Recording what actually shipped
// is the point. Nothing depends on it; the URL is keyed by hash.
const version =
  text.match(/ETHORA_CHAT_ASSISTANT_VERSION\s*=\s*["'](\d[\d.]*)["']/)?.[1] ?? pkg.version;

writeFileSync(
  resolve(root, 'src/generated/bundledWidget.ts'),
  `// GENERATED by scripts/copy-widget.mjs (npm prebuild). Do not edit by hand.
//
// Committed so \`npm run typecheck\` works on a fresh clone; every build
// overwrites it from whatever ${PKG} the lockfile pins.
export const BUNDLED_WIDGET_VERSION = '${version}';
export const BUNDLED_WIDGET_PATH = '/widget/${fileName}';
`
);

const kb = Math.round(statSync(src).size / 1024);
console.log(
  `[copy-widget] ${PKG}@${pkg.version} (reports ${version}) -> public/widget/${fileName} (${kb} KB)`
);
