#!/usr/bin/env node
// Copies a freshly built AI widget bundle into public/widget/ and points the
// app at it. Run by hand after building the widget, NOT during deploy:
//
//   cd ../ai-assistant-ui && npx vite build --minify false
//   cd ../ethora-app-reactjs && npm run widget:sync
//   git add public/widget src/generated/bundledWidget.ts && git commit
//
// Why the bundle is committed rather than installed.
//
// The widget URL used to live only in VITE_WIDGET_URL, a build-time string
// Vite inlines into the admin bundle. On QA it read
// https://widget.chat-qa.ethora.com/assistant2604.js: an April build, on a
// static host with its own separate deploy that nobody re-ran. Nothing tied
// that string to a version of the widget, so it rotted silently while the
// admin kept handing operators an embed snippet pointing at a bundle older
// than the /v2/widget/sessions flow it depends on.
//
// The obvious fix, `"@ethora/ai-chat-widget": "github:dappros/ai-assistant-ui#<sha>"`,
// no longer works. It worked once, at 77f6a48, because that revision had
// `"prepare": "npm run build:package"` and npm builds git dependencies on
// install. Today the widget has no `prepare`, no vite.lib.config.ts, `dist`
// is gitignored, and its build resolves @ethora/chat-component from the
// SIBLING checkout (`../ethora-chat-component/src`, vite.config.ts) - a path
// that does not exist inside node_modules. A git install would therefore
// produce a package whose "main" points at a file that was never built, and
// npm would not complain, because nothing here imports the package: the
// widget is loaded as <script src>, not as a module.
//
// Publishing to npm would work, but that is a release step gated on someone
// having publish rights. Committing the built file needs nothing: it deploys
// with the app, from the app's own origin, and the version that ships is
// visible in git history.
//
// The filename carries a content hash, so a changed bundle is always a new
// URL (visitors cannot get a stale cached copy) and an unchanged bundle is
// always the same URL (no pointless churn in git).

import { createHash } from 'node:crypto';
import { copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// Default location: the sibling widget checkout, as laid out in the ethora
// workspace. Override for a build produced elsewhere.
const src =
  process.argv[2] || resolve(root, '../ai-assistant-ui/dist/ethora_assistant.js');

const die = (msg) => {
  console.error(`\n[widget:sync] ${msg}\n`);
  process.exit(1);
};

let bytes;
try {
  bytes = readFileSync(src);
} catch {
  die(
    `no bundle at ${src}\n` +
      `  Build it first:  cd ../ai-assistant-ui && npx vite build --minify false\n` +
      `  Or pass a path:  npm run widget:sync -- /path/to/ethora_assistant.js`
  );
}

// Cheap sanity check. A build that silently produced the wrong entry (the
// library build, say) would still be a large plausible-looking JS file, and
// the failure would only surface as a dead widget on QA.
const text = bytes.toString('utf8');
for (const marker of ['chat-content-assistant', 'data-app-id', 'widget/sessions']) {
  if (!text.includes(marker)) {
    die(`${src} does not look like the embed bundle: "${marker}" not found in it.`);
  }
}

const hash = createHash('sha256').update(bytes).digest('hex').slice(0, 8);
const fileName = `assistant-${hash}.js`;
const outDir = resolve(root, 'public/widget');

// Drop older bundles: keeping them would leave dead 3 MB files in the deploy
// answering requests from embeds we would rather see fail loudly.
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });
copyFileSync(src, resolve(outDir, fileName));

// The version the bundle REPORTS, read from the one declaration the widget
// publishes on `window.EthoraAssistant.version`. Deliberately not taken from
// the widget repo's package.json: those two drift (the bundle currently in
// this tree says 25.10.17 while the repo has moved to 26.7.1, because it was
// built one commit before the bump), and the whole point of this file is to
// record what actually shipped. Nothing depends on it - the URL is keyed by
// content hash - so an unparseable bundle is not fatal.
const version =
  text.match(/ETHORA_CHAT_ASSISTANT_VERSION\s*=\s*["'](\d[\d.]*)["']/)?.[1] ?? 'unknown';

writeFileSync(
  resolve(root, 'src/generated/bundledWidget.ts'),
  `// GENERATED by scripts/sync-widget.mjs. Do not edit by hand.
//
// Points at the widget bundle committed under public/widget/. Regenerate by
// building ../ai-assistant-ui and running \`npm run widget:sync\`.
export const BUNDLED_WIDGET_VERSION = '${version}';
export const BUNDLED_WIDGET_PATH = '/widget/${fileName}';
`
);

const kb = Math.round(statSync(src).size / 1024);
console.log(
  `[widget:sync] ${src}\n` +
    `           -> public/widget/${fileName} (${kb} KB, widget version ${version})\n` +
    `              commit public/widget/ and src/generated/bundledWidget.ts`
);
